// Bundles ../presets/preset-*.js (and the two loose sketches) into presets.js so the
// sandbox works from file:// as well as http:// (fetch() is blocked on file://).
// Re-run after editing a preset:   node build-presets.mjs
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const root = join(here, '..', 'presets')

const entries = [
  { id: 'preset-1', label: 'Preset 1', file: 'preset-1.js' },
  { id: 'preset-2', label: 'Preset 2', file: 'preset-2.js' },
  { id: 'preset-3', label: 'Preset 3', file: 'preset-3.js' },
  { id: 'preset-4', label: 'Preset 4', file: 'preset-4.js' },
  { id: 'preset-5', label: 'Preset 5', file: 'preset-5.js' },
  { id: 'preset-base', label: 'Base (preset.js)', file: 'preset.js' },
  { id: 'sketch-814b', label: 'Sketch 814b', file: 'sketch-814b-no-arrows.js' },
]

const presets = []
for (const e of entries) {
  const p = join(root, e.file)
  if (!existsSync(p)) { console.warn('skip (missing):', e.file); continue }
  presets.push({ ...e, source: readFileSync(p, 'utf8').replace(/\r\n/g, '\n').trim() })
}

const out = `// GENERATED by build-presets.mjs on ${new Date().toISOString()} — do not edit by hand.\n` +
  `window.PRESETS = ${JSON.stringify(presets, null, 2)};\n`
writeFileSync(join(here, 'presets.js'), out)
console.log(`wrote presets.js with ${presets.length} presets`)
